apiVersion: v1
kind: Secret
metadata:
  name: hybrid-api-secret
  labels:
    app: hybrid-auth-service
type: Opaque
stringData:  # Kubernetes codifica autom√°ticamente
  JWT_ACCESS_TOKEN: "jwtHybridApi2025"
  JWT_REFRESH_TOKEN: "jwtHybridSecretApi2025"
  DB_USERNAME: iv_hybrid_api
  DB_PASSWORD: qMyVhx38d2XS1FGWgi9T
  EMAIL_HOST: mail.hybrid.com.ve
  EMAIL_PORT: "587"
  EMAIL_USER: info.hybrid
  EMAIL_PASSWORD: "*info123@*"
  EMAIL_FROM: info@hybrid.com.ve
  EMAIL_FROM_NAME: Hybrid
  FRONTEND_URL: http://localhost:4200
  RESEND_API_KEY: re_Z1dcUS9M_G5zsfC5UdAVUr67PFe7gaW72